"""Digital twin simulation endpoints.

All values served here are SIMULATED FOR DIGITAL TWIN DEMONSTRATION -
generated by the backend engine, never real telemetry. The response model
carries the disclaimer on every request.
"""

from fastapi import APIRouter

from app.schemas.models import SimulationStatus
from app.services import simulation

router = APIRouter(prefix="/api/simulation", tags=["Digital Twin Simulation"])


@router.get("/status", response_model=SimulationStatus,
            summary="Current simulated traffic / parking / EV state")
def status() -> dict:
    return simulation.status()
