/**
 * Digital twin simulation overlays.
 *
 * ALL data shown by this module is SIMULATED FOR DIGITAL TWIN DEMONSTRATION —
 * generated by the backend engine (Markov-style transitions every 60 s),
 * never real telemetry. The disclaimer is rendered in the panel and on every
 * simulated map feature.
 */
import { CONFIG } from "../config.js";
import { apiGet } from "./api.js";
import { restyle } from "./layers.js";

/* global Cesium */

const TRAFFIC_COLORS = {
  low: "#35c4a2", moderate: "#d8b447", high: "#e0824f", severe: "#e2604f",
};
const PARKING_COLORS = { available: "#35c4a2", limited: "#d8b447", full: "#e2604f" };
const EV_COLORS = { available: "#35c4a2", busy: "#d8b447", offline: "#8a8f99" };

const SIM_TAG = "Simulated for Digital Twin Demonstration";

export function summarize(items, key = "status") {
  const counts = {};
  for (const item of items) counts[item[key]] = (counts[item[key]] ?? 0) + 1;
  return counts;
}

function legend(colors, counts) {
  return Object.entries(colors)
    .map(([status, color]) => `
      <span class="sim-chip">
        <span class="layer-swatch" style="background:${color}"></span>
        ${status} <strong>${counts[status] ?? 0}</strong>
      </span>`)
    .join("");
}

function simDescription(title, rows) {
  return `
    <style>.attr-table{width:100%;border-collapse:collapse;font-size:13px}
      .attr-table th{text-align:left;padding:3px 10px 3px 0;color:#9fb0ce;white-space:nowrap}
      .sim-warn{color:#f0b23e;font-size:11px;margin-top:8px}</style>
    <table class="attr-table">${rows.join("")}</table>
    <p class="sim-warn">⚠ ${SIM_TAG} — not real telemetry.</p>`;
}

export function initSimulation(viewer, layerManager) {
  const content = document.getElementById("twin-content");
  content.innerHTML = `
    <label class="layer-item"><input type="checkbox" id="sim-traffic" />
      <span class="layer-swatch" style="background:#e0824f"></span>
      <span class="layer-name">Traffic status (roads)</span></label>
    <div class="sim-legend" id="legend-traffic"></div>

    <label class="layer-item"><input type="checkbox" id="sim-parking" />
      <span class="layer-swatch" style="background:#d8b447"></span>
      <span class="layer-name">Parking occupancy</span></label>
    <div class="sim-legend" id="legend-parking"></div>

    <label class="layer-item"><input type="checkbox" id="sim-ev" />
      <span class="layer-swatch" style="background:#35c4a2"></span>
      <span class="layer-name">EV charger availability</span></label>
    <div class="sim-legend" id="legend-ev"></div>

    <p class="panel-note" id="sim-updated"></p>`;

  const pointSource = new Cesium.CustomDataSource("simulation-points");
  viewer.dataSources.add(pointSource);

  const state = {
    data: null,
    traffic: false,
    parking: false,
    ev: false,
  };

  // ------------------------------------------------------------------ traffic
  function applyTraffic() {
    const roadsItem = layerManager.state.get("roads");
    const dataSource = roadsItem?.dataSource;
    if (!dataSource) return;
    const statusByRoad = new Map(
      state.data.traffic.map((t) => [String(t.road_id), t])
    );
    for (const entity of dataSource.entities.values) {
      if (!entity.polyline) continue;
      const sim = statusByRoad.get(String(entity.id));
      if (sim) {
        entity.polyline.material = Cesium.Color.fromCssColorString(
          TRAFFIC_COLORS[sim.status]
        );
        entity.polyline.width = 4;
        entity.description = simDescription("Traffic", [
          `<tr><th>Road</th><td>${entity.name ?? entity.id}</td></tr>`,
          `<tr><th>Simulated status</th><td>${sim.status}</td></tr>`,
          `<tr><th>Speed factor</th><td>${sim.speed_factor}</td></tr>`,
        ]);
      } else {
        entity.polyline.material = Cesium.Color.fromCssColorString("#5a6070").withAlpha(0.6);
      }
    }
    viewer.scene.requestRender();
  }

  function clearTraffic() {
    const dataSource = layerManager.state.get("roads")?.dataSource;
    if (dataSource) restyle(dataSource, "roads");
    viewer.scene.requestRender();
  }

  // ------------------------------------------------------- parking & EV points
  function applyPoints() {
    pointSource.entities.removeAll();
    if (state.parking && state.data) {
      for (const p of state.data.parking) {
        pointSource.entities.add({
          position: Cesium.Cartesian3.fromDegrees(p.lon, p.lat, 2),
          point: {
            pixelSize: 11,
            color: Cesium.Color.fromCssColorString(PARKING_COLORS[p.status]),
            outlineColor: Cesium.Color.fromCssColorString("#0d1220"),
            outlineWidth: 2,
            disableDepthTestDistance: Number.POSITIVE_INFINITY,
          },
          name: `${p.name ?? "Parking"} [SIM]`,
          description: simDescription("Parking", [
            `<tr><th>Name</th><td>${p.name ?? "(unnamed)"}</td></tr>`,
            `<tr><th>Simulated status</th><td>${p.status}</td></tr>`,
            `<tr><th>Simulated occupancy</th><td>${p.occupancy_pct}%</td></tr>`,
          ]),
        });
      }
    }
    if (state.ev && state.data) {
      for (const c of state.data.ev_chargers) {
        pointSource.entities.add({
          position: Cesium.Cartesian3.fromDegrees(c.lon, c.lat, 2),
          point: {
            pixelSize: 11,
            color: Cesium.Color.fromCssColorString(EV_COLORS[c.status]),
            outlineColor: Cesium.Color.fromCssColorString("#0d1220"),
            outlineWidth: 2,
            disableDepthTestDistance: Number.POSITIVE_INFINITY,
          },
          name: `${c.name ?? "EV charger"} [SIM]`,
          description: simDescription("EV charger", [
            `<tr><th>Name</th><td>${c.name ?? "(unnamed)"}</td></tr>`,
            `<tr><th>Simulated status</th><td>${c.status}</td></tr>`,
          ]),
        });
      }
    }
    viewer.scene.requestRender();
  }

  // ---------------------------------------------------------------- refresh
  async function refresh() {
    try {
      state.data = await apiGet("/api/simulation/status");
      document.getElementById("legend-traffic").innerHTML =
        legend(TRAFFIC_COLORS, summarize(state.data.traffic));
      document.getElementById("legend-parking").innerHTML =
        legend(PARKING_COLORS, summarize(state.data.parking));
      document.getElementById("legend-ev").innerHTML =
        legend(EV_COLORS, summarize(state.data.ev_chargers));
      document.getElementById("sim-updated").textContent =
        `Engine state: ${state.data.traffic.length} roads, ` +
        `${state.data.parking.length} parking, ${state.data.ev_chargers.length} chargers · ` +
        `refreshed ${new Date().toLocaleTimeString()}`;
      if (state.traffic) applyTraffic();
      applyPoints();
    } catch (err) {
      document.getElementById("sim-updated").textContent =
        `Simulation unavailable: ${err.message}`;
    }
  }

  // ----------------------------------------------------------------- wiring
  document.getElementById("sim-traffic").addEventListener("change", async (e) => {
    state.traffic = e.target.checked;
    if (state.traffic) {
      // Traffic colours the roads layer; make sure it is loaded & visible.
      await layerManager.ensureLoaded("roads");
      layerManager.setVisible("roads", true);
      const roadsToggle = document.querySelector("#count-roads")
        ?.closest(".layer-item")?.querySelector("input");
      if (roadsToggle) roadsToggle.checked = true;
      if (state.data) applyTraffic();
    } else {
      clearTraffic();
    }
  });
  document.getElementById("sim-parking").addEventListener("change", (e) => {
    state.parking = e.target.checked;
    applyPoints();
  });
  document.getElementById("sim-ev").addEventListener("change", (e) => {
    state.ev = e.target.checked;
    applyPoints();
  });

  refresh();
  setInterval(refresh, CONFIG.SIMULATION_REFRESH_MS);
}
