-- =====================================================================
-- Smart City Digital Twin - 04: Digital twin simulation tables
--
-- IMPORTANT: everything in these tables is SIMULATED FOR DIGITAL TWIN
-- DEMONSTRATION. It is generated by the backend simulation engine and
-- must never be presented as official real-time data. Every row carries
-- is_simulated = TRUE and a fixed disclaimer.
-- =====================================================================

-- Traffic status per (major) road segment
CREATE TABLE IF NOT EXISTS sim_traffic_status (
    id            BIGSERIAL PRIMARY KEY,
    road_id       BIGINT NOT NULL REFERENCES roads(id) ON DELETE CASCADE,
    status        TEXT   NOT NULL CHECK (status IN ('low', 'moderate', 'high', 'severe')),
    speed_factor  NUMERIC(3,2) NOT NULL DEFAULT 1.0
        CHECK (speed_factor > 0 AND speed_factor <= 1.0),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_simulated  BOOLEAN NOT NULL DEFAULT TRUE CHECK (is_simulated),
    disclaimer    TEXT NOT NULL DEFAULT 'Simulated for Digital Twin Demonstration',
    CONSTRAINT sim_traffic_road_uniq UNIQUE (road_id)
);

-- Parking occupancy per parking facility
CREATE TABLE IF NOT EXISTS sim_parking_status (
    id             BIGSERIAL PRIMARY KEY,
    facility_id    BIGINT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    status         TEXT   NOT NULL CHECK (status IN ('available', 'limited', 'full')),
    occupancy_pct  NUMERIC(5,1) NOT NULL CHECK (occupancy_pct BETWEEN 0 AND 100),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_simulated   BOOLEAN NOT NULL DEFAULT TRUE CHECK (is_simulated),
    disclaimer     TEXT NOT NULL DEFAULT 'Simulated for Digital Twin Demonstration',
    CONSTRAINT sim_parking_facility_uniq UNIQUE (facility_id)
);

-- EV charger availability per charging station
CREATE TABLE IF NOT EXISTS sim_ev_status (
    id            BIGSERIAL PRIMARY KEY,
    facility_id   BIGINT NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    status        TEXT   NOT NULL CHECK (status IN ('available', 'busy', 'offline')),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_simulated  BOOLEAN NOT NULL DEFAULT TRUE CHECK (is_simulated),
    disclaimer    TEXT NOT NULL DEFAULT 'Simulated for Digital Twin Demonstration',
    CONSTRAINT sim_ev_facility_uniq UNIQUE (facility_id)
);

COMMENT ON TABLE sim_traffic_status IS 'SIMULATED demonstration data - not real traffic.';
COMMENT ON TABLE sim_parking_status IS 'SIMULATED demonstration data - not real occupancy.';
COMMENT ON TABLE sim_ev_status     IS 'SIMULATED demonstration data - not real charger telemetry.';
